version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
  
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend